# Generated by Django 2.0.4 on 2018-05-23 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstrumentType', models.CharField(choices=[('acousticguitar', 'Acoustic Guitar'), ('electricguitar', 'Electric Guitar'), ('bassguitar', 'Bass Guitar'), ('piano', 'Piano'), ('cello', 'Cello'), ('drums', 'Drums'), ('violin', 'Violin'), ('saxophone', 'Saxophone'), ('harmonium', 'Harmonium'), ('tablas', 'Tablas'), ('santurs', 'Santurs'), ('vina', 'Vina')], max_length=20, verbose_name='Instrument')),
                ('InstrumentCondition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('repair', 'Repair'), ('discard', 'Discard')], max_length=9, verbose_name='Condition')),
                ('HireCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('PhoneNumber', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.CharField(choices=[('mon', 'Mon'), ('tues', 'Tues'), ('wed', 'Wed'), ('thurs', 'Thurs'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=20, verbose_name='Days')),
                ('Times', models.CharField(choices=[('7', '7am'), ('8', '8am'), ('9', '9am'), ('10', '10am'), ('11', '11am'), ('12', '12pm'), ('13', '1pm'), ('14', '2pm'), ('15', '3pm'), ('16', '4pm'), ('17', '5pm'), ('18', '6pm'), ('19', '7pm')], max_length=15, verbose_name='Times')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInstruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstrumentType', models.CharField(choices=[('acousticguitar', 'Acoustic Guitar'), ('electricguitar', 'Electric Guitar'), ('bassguitar', 'Bass Guitar'), ('piano', 'Piano'), ('cello', 'Cello'), ('drums', 'Drums'), ('violin', 'Violin'), ('saxophone', 'Saxophone'), ('harmonium', 'Harmonium'), ('tablas', 'Tablas'), ('santurs', 'Santurs'), ('vina', 'Vina')], max_length=20, verbose_name='InstrumentSkillLevel')),
                ('InstrumentSkillLevel', models.CharField(choices=[('expert', 'Expert'), ('high', 'High'), ('medicore', 'Medicore')], max_length=20, verbose_name='InstrumentSkillLevel')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LanguageSkillLevel', models.CharField(choices=[('expert', 'Expert'), ('high', 'High'), ('medicore', 'Medicore')], max_length=20, verbose_name='LanguageSkillLevel')),
                ('Languages', models.CharField(choices=[('english', 'English'), ('chinese', 'Chinese'), ('spanish', 'Spanish'), ('hindi', 'Hindi'), ('arabic', 'Arabic'), ('portuguese', 'Portuguese'), ('bengali', 'Bengali'), ('russian', 'Russian'), ('japanese', 'Japanese'), ('punjabi', 'Punjabi')], max_length=20, verbose_name='Languages')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=60)),
                ('LastName', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('UserType', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7)),
                ('FacebookID', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='teacherlanguage',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewModels.Users'),
        ),
        migrations.AddField(
            model_name='teacherinstruments',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewModels.Users'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='StudentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users_Student_Availibility', to='NewModels.Users'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users_Teacher_Availibility', to='NewModels.Users'),
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewModels.Users'),
        ),
        migrations.AddField(
            model_name='instruments',
            name='Hiredby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NewModels.Users'),
        ),
        migrations.AddField(
            model_name='contract',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users_Student_Contract', to='NewModels.Users'),
        ),
        migrations.AddField(
            model_name='contract',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users_Teacher_Contract', to='NewModels.Users'),
        ),
    ]
