# Generated by Django 2.0.4 on 2018-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_auto_20180526_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstrumentType', models.CharField(choices=[('acousticguitar', 'Acoustic Guitar'), ('electricguitar', 'Electric Guitar'), ('bassguitar', 'Bass Guitar'), ('piano', 'Piano'), ('cello', 'Cello'), ('drums', 'Drums'), ('violin', 'Violin'), ('saxophone', 'Saxophone'), ('harmonium', 'Harmonium'), ('tablas', 'Tablas'), ('santurs', 'Santurs'), ('vina', 'Vina')], max_length=20, verbose_name='Instrument')),
                ('InstrumentCondition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('repair', 'Repair'), ('discard', 'Discard')], max_length=9, verbose_name='Condition')),
                ('HireCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.CharField(choices=[('mon', 'Mon'), ('tues', 'Tues'), ('wed', 'Wed'), ('thurs', 'Thurs'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=20, verbose_name='Days')),
                ('Times', models.CharField(choices=[('7', '7am'), ('8', '8am'), ('9', '9am'), ('10', '10am'), ('11', '11am'), ('12', '12pm'), ('13', '1pm'), ('14', '2pm'), ('15', '3pm'), ('16', '4pm'), ('17', '5pm'), ('18', '6pm'), ('19', '7pm')], max_length=15, verbose_name='Times')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInstruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstrumentType', models.CharField(choices=[('acousticguitar', 'Acoustic Guitar'), ('electricguitar', 'Electric Guitar'), ('bassguitar', 'Bass Guitar'), ('piano', 'Piano'), ('cello', 'Cello'), ('drums', 'Drums'), ('violin', 'Violin'), ('saxophone', 'Saxophone'), ('harmonium', 'Harmonium'), ('tablas', 'Tablas'), ('santurs', 'Santurs'), ('vina', 'Vina')], max_length=20, verbose_name='InstrumentSkillLevel')),
                ('InstrumentSkillLevel', models.CharField(choices=[('expert', 'Expert'), ('high', 'High'), ('medicore', 'Medicore')], max_length=20, verbose_name='InstrumentSkillLevel')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LanguageSkillLevel', models.CharField(choices=[('expert', 'Expert'), ('high', 'High'), ('medicore', 'Medicore')], max_length=20, verbose_name='LanguageSkillLevel')),
                ('Languages', models.CharField(choices=[('english', 'English'), ('chinese', 'Chinese'), ('spanish', 'Spanish'), ('hindi', 'Hindi'), ('arabic', 'Arabic'), ('portuguese', 'Portuguese'), ('bengali', 'Bengali'), ('russian', 'Russian'), ('japanese', 'Japanese'), ('punjabi', 'Punjabi')], max_length=20, verbose_name='Languages')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
