# Generated by Django 2.0.4 on 2018-05-29 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_instruments_hiredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='Hiredby',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
