# Generated by Django 2.0.4 on 2018-05-30 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0007_auto_20180529_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentFirstName', models.CharField(max_length=100, null=True)),
                ('StudentLastName', models.CharField(max_length=100, null=True)),
                ('TeacherFirstName', models.CharField(max_length=100, null=True)),
                ('TeacherLastName', models.CharField(max_length=100, null=True)),
                ('TeacherInstrument', models.CharField(max_length=100, null=True)),
                ('TeacherLanguage', models.CharField(max_length=100, null=True)),
                ('LessonStartTime', models.CharField(choices=[('7', '7am'), ('8', '8am'), ('9', '9am'), ('10', '10am'), ('11', '11am'), ('12', '12pm'), ('13', '1pm'), ('14', '2pm'), ('15', '3pm'), ('16', '4pm'), ('17', '5pm'), ('18', '6pm'), ('19', '7pm')], max_length=20, verbose_name='LessonStartTime')),
                ('LessonEndTime', models.CharField(choices=[('7', '7am'), ('8', '8am'), ('9', '9am'), ('10', '10am'), ('11', '11am'), ('12', '12pm'), ('13', '1pm'), ('14', '2pm'), ('15', '3pm'), ('16', '4pm'), ('17', '5pm'), ('18', '6pm'), ('19', '7pm')], max_length=20, verbose_name='LessonEndTIme')),
                ('LessonDay', models.CharField(choices=[('mon', 'Mon'), ('tues', 'Tues'), ('wed', 'Wed'), ('thurs', 'Thurs'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=20, verbose_name='LessonDay')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentID_LessonBookings', to=settings.AUTH_USER_MODEL)),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeacherID_LessonBookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
