# Generated by Django 2.0.4 on 2018-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_lessonbookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonbookings',
            name='StudentID',
        ),
        migrations.RemoveField(
            model_name='lessonbookings',
            name='TeacherID',
        ),
        migrations.AddField(
            model_name='lessonbookings',
            name='StudentEmail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lessonbookings',
            name='TeacherInstrument',
            field=models.CharField(choices=[('acousticguitar', 'Acoustic Guitar'), ('electricguitar', 'Electric Guitar'), ('bassguitar', 'Bass Guitar'), ('piano', 'Piano'), ('cello', 'Cello'), ('drums', 'Drums'), ('violin', 'Violin'), ('saxophone', 'Saxophone'), ('harmonium', 'Harmonium'), ('tablas', 'Tablas'), ('santurs', 'Santurs'), ('vina', 'Vina')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lessonbookings',
            name='TeacherLanguage',
            field=models.CharField(choices=[('english', 'English'), ('chinese', 'Chinese'), ('spanish', 'Spanish'), ('hindi', 'Hindi'), ('arabic', 'Arabic'), ('portuguese', 'Portuguese'), ('bengali', 'Bengali'), ('russian', 'Russian'), ('japanese', 'Japanese'), ('punjabi', 'Punjabi')], max_length=100, null=True),
        ),
    ]
