# Generated by Django 2.0.4 on 2018-04-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=60)),
                ('LastName', models.CharField(max_length=60)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=1)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('FacebookID', models.CharField(max_length=121)),
                ('TeacherInstruments', models.CharField(choices=[('acousticguitar', 'Acoustic Guitar'), ('electricguitar', 'Electric Guitar'), ('bassguitar', 'Bass Guitar'), ('piano', 'Piano'), ('cello', 'Cello'), ('drums', 'Drums'), ('violin', 'Violin'), ('saxophone', 'Saxophone'), ('harmonium', 'Harmonium'), ('tablas', 'Tablas'), ('santurs', 'Santurs'), ('vina', 'Vina')], max_length=1)),
                ('LessonDays', models.CharField(choices=[('mon', 'Mon'), ('tues', 'Tues'), ('wed', 'Wed'), ('thurs', 'Thurs'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=1)),
                ('LessonTime', models.DateTimeField()),
                ('TeacherLanguageSkills', models.CharField(choices=[('english', 'English'), ('chinese', 'Chinese')], max_length=1)),
                ('TeacherGender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=1)),
            ],
        ),
    ]
