# Generated by Django 2.0.4 on 2018-04-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admins_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7),
        ),
        migrations.AlterField(
            model_name='students',
            name='LessonDays',
            field=models.CharField(choices=[('mon', 'Mon'), ('tues', 'Tues'), ('wed', 'Wed'), ('thurs', 'Thurs'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=3),
        ),
        migrations.AlterField(
            model_name='students',
            name='TeacherGender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7),
        ),
        migrations.AlterField(
            model_name='students',
            name='TeacherInstruments',
            field=models.CharField(choices=[('acousticguitar', 'Acoustic Guitar'), ('electricguitar', 'Electric Guitar'), ('bassguitar', 'Bass Guitar'), ('piano', 'Piano'), ('cello', 'Cello'), ('drums', 'Drums'), ('violin', 'Violin'), ('saxophone', 'Saxophone'), ('harmonium', 'Harmonium'), ('tablas', 'Tablas'), ('santurs', 'Santurs'), ('vina', 'Vina')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='TeacherLanguageSkills',
            field=models.CharField(choices=[('english', 'English'), ('chinese', 'Chinese')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Instruments',
            field=models.CharField(choices=[('acousticguitar', 'Acoustic Guitar'), ('electricguitar', 'Electric Guitar'), ('bassguitar', 'Bass Guitar'), ('piano', 'Piano'), ('cello', 'Cello'), ('drums', 'Drums'), ('violin', 'Violin'), ('saxophone', 'Saxophone'), ('harmonium', 'Harmonium'), ('tablas', 'Tablas'), ('santurs', 'Santurs'), ('vina', 'Vina')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7),
        ),
    ]
