# Generated by Django 2.0.4 on 2018-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180428_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='LessonDays',
            field=models.CharField(choices=[('mon', 'Mon'), ('tues', 'Tues'), ('wed', 'Wed'), ('thurs', 'Thurs'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=5),
        ),
    ]
