# Generated by Django 2.0.4 on 2018-04-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180428_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstrumentType', models.CharField(choices=[('acousticguitar', 'Acoustic Guitar'), ('electricguitar', 'Electric Guitar'), ('bassguitar', 'Bass Guitar'), ('piano', 'Piano'), ('cello', 'Cello'), ('drums', 'Drums'), ('violin', 'Violin'), ('saxophone', 'Saxophone'), ('harmonium', 'Harmonium'), ('tablas', 'Tablas'), ('santurs', 'Santurs'), ('vina', 'Vina')], max_length=20)),
                ('InstrumentCondition', models.CharField(choices=[('excellent', 'Excellent'), ('verygood', 'VeryGood'), ('mediocre', 'Mediocre'), ('poor', 'Poor')], max_length=9)),
            ],
        ),
    ]
