# Generated by Django 2.0.4 on 2018-04-29 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_instruments'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeachingDays', models.CharField(choices=[('mon', 'Mon'), ('tues', 'Tues'), ('wed', 'Wed'), ('thurs', 'Thurs'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=5)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('ScheduleStatus', models.CharField(choices=[('full', 'Full'), ('empty', 'Empty')], max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='admins',
            name='FacebookID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='InstrumentCondition',
            field=models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('repair', 'Repair'), ('discard', 'Discard')], max_length=9),
        ),
        migrations.AlterField(
            model_name='students',
            name='FacebookID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='TeacherLanguageSkills',
            field=models.CharField(choices=[('english', 'English'), ('chinese', 'Chinese'), ('spanish', 'Spanish'), ('hindi', 'Hindi'), ('arabic', 'Arabic'), ('portuguese', 'Portuguese'), ('bengali', 'Bengali'), ('russian', 'Russian'), ('japanese', 'Japanese'), ('punjabi', 'Punjabi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='FacebookID',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='teachingschedule',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teachers'),
        ),
        migrations.AddField(
            model_name='instrumenthire',
            name='Instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Instruments'),
        ),
        migrations.AddField(
            model_name='instrumenthire',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
    ]
